[project]
name = "all-the-data-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "argparse>=1.4.0",
    "discord>=2.3.2",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "requests>=2.32.5",
]
